#!/usr/bin/env python
from pushsafer import Client
import serial
import time

clientpush = Client("", privatekey="gHIXO4mnMUAcsKfTJieY")
clientpush.send_message(message="Pihatcher",
                        title="Initiated",
                        device="a",
                        sound="",
                        vibration="",
                        icon="1",
                        url="",
                        urltitle="",
                        time2live="3600",
                        priority="0",
                        picture1="",
                        picture2="",
                        picture3="",
                        expire="3600",
                        retry="3600",
                        answer=0)
